feat: Time limited Secrets. Can be used with aiven-kafka-topics debugging tool: Debuk
nais/aivenator pull request #4
Opened 2021-09-02 11:55 UTC by ybelMekk

Names and appearance of structs could be discussed.

Feature will help developers debug a topic/application for an `expiredAt` timestamp. This do not have a limt.

This feature can be used with tool: https://github.com/nais/debuk.

2021-09-03 13:02 UTC, mortenlj requested changes

2021-09-03 13:02 UTC, mortenlj commented on pkg/handlers/secret/secret.go
> +			constants.AivenatorProtectedTimeToLiveAnnotation: time.Now().String(),
I `janitor.go` linje 118 (https://github.com/nais/aivenator/pull/4/files#diff-1198131901acde95c353d2a77725f1f0c6e2abf17f4855df5a6cf1a5ed1a00b8R118) så sjekker du om denne annotasjonen er `true`, men her settes den til timestamp. En av dem er feil.

2021-09-03 13:45 UTC, ybelMekk commented
Her er de noen som ikke skjønt noe ass 😬😅

2021-09-03 14:01 UTC, ybelMekk commented on pkg/credentials/janitor.go
>  				counters.Protected += 1
vet ikke helt hvorfor jeg itererte i den andre blokken, var her jeg implementerte de først, men endret meg av noen grunn jeg ikke husker

2021-09-07 11:58 UTC, mortenlj requested changes

2021-09-07 11:58 UTC, mortenlj commented on controllers/aiven_application/reconciler.go
> +	logger = logger.WithFields(log.Fields{
Denne loggeren har allerede disse feltene satt.

2021-09-07 11:58 UTC, mortenlj commented on controllers/aiven_application/reconciler.go
> +			logger.Warningf("application do not exist in cluster: %s", err)
Hvis man får 404 NotFound når man prøver å slette noe, så har man oppnådd det man ønsket. Ikke nødvendig å logge noe mer enn `Debug` her vel?

2021-09-07 11:58 UTC, mortenlj commented on controllers/aiven_application/reconciler.go
> +			return fail(err)
Her kan du nok med fordel sørge for å kalle `utils.LocalFail` med en beskrivende "reason" før du returnerer.

2021-09-07 11:58 UTC, mortenlj commented on pkg/handlers/kafka/kafka.go
> +	DeleteExpiredAnnotation = "kafka.aiven.nais.io/expired"
Denne annotasjonen trenger ikke (er ikke) Kafka-spesifik, så den burde ikke ligge her, og ikke hete `kafka.aiven...`. Den burde hete `aivenator.aiven.nais.io/expired`, og ligge et annet sted, nærmere der den blir brukt.

2021-09-07 11:58 UTC, mortenlj commented on controllers/aiven_application/reconciler.go
> +	if ok := annotations.HasDelete(application.GetAnnotations()); ok {
Her kan man bare se på `spec.ExpiresAt` feltet, trenger ikke gå omveien ved å sette en annotasjon som man reagerer på her.

2021-09-08 08:36 UTC, mortenlj approved these changes
Ser bra ut nå :+1:

2021-09-08 08:44 UTC, ybelMekk commented
ok, etter grønt lys, merger, og oppdaterer doc.

2021-09-08 08:47 UTC, ybelMekk commented
Men first, liberator

2021-09-09 14:04 UTC, merged